Fixed too many levels of symbolic links issue

diff --git a/add b/add
--- a/add
+++ b/add
@@ -2,14 +2,16 @@
 
 DIRECTORY="/mnt/games/SteamLibrary"
 CFG_PATH="$DIRECTORY/steamapps/common/Counter-Strike\ Global\ Offensive/game/csgo/cfg"
-CFG_PATH_ESCAPED="${CFG_PATH//\\ / }"                                              
+CFG_PATH_ESCAPED="${CFG_PATH//\\ / }"
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 for file in *.cfg; do 
 	if [ -L "$CFG_PATH_ESCAPED/$file" ]; then
-		echo -e "\e[33mSkipped: $file (already linked)\e[0m"
+		rm "$CFG_PATH_ESCAPED/$file"
+		ln -s "$SCRIPT_DIR/$file" "$CFG_PATH_ESCAPED/$file" && echo -e "\e[36mRelinked: $file\e[0m" || echo -e "\e[31mFailed to relink: $file\e[0m"
 	elif [ -e "$CFG_PATH_ESCAPED/$file" ]; then
 		echo -e "\e[33mSkipped: $file (file already exists)\e[0m"
-	elif ln -s "./$file" "$CFG_PATH_ESCAPED/$file" 2>/dev/null; then
+	elif ln -s "$SCRIPT_DIR/$file" "$CFG_PATH_ESCAPED/$file" 2>/dev/null; then
 		echo -e "\e[32mLinked: $file -> $CFG_PATH_ESCAPED/$file\e[0m"
 	else
 		echo -e "\e[31mFailed to link: $file\e[0m"
